name: Build and Push to GHCR

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare lowercase repository name
        id: lowercase
        run: |
          echo "repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --tag ghcr.io/${{ steps.lowercase.outputs.repo }}:latest \
            --tag ghcr.io/${{ steps.lowercase.outputs.repo }}:${{ github.ref_name }} \
            --tag ghcr.io/${{ steps.lowercase.outputs.repo }}:${{ github.sha }} \
            --push .

